#!/bin/sh

# Jolla btrfs root mounting script
#
# Copyright (C) 2014 Jolla Ltd.
# Contact: Kalle Jokiniemi <kalle.jokiniemi@jolla.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

ROOTDEV="/dev/mmcblk0p28"

if [ -z $1 ] || [ ! -e $1 ]; then
	echo "Please pass mount point as parameter!"
	exit 1
fi

if mount -t btrfs -o recovery $ROOTDEV $1; then
	echo "Root mounted"
	exit 0
else
	echo "Root mounting failed, trying recovery options"
	if mount -t btrfs -o recovery,clear_cache,autodefrag $ROOTDEV $1; then
		echo "Root mounted with recovery options"
		exit 0
	else
		echo "Jolla root mounting failed"
		exit 1
	fi
fi

